name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: pkg install
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install git -y
    - name: git begonia kernel code
      run: git clone --branch begonia-r-oss --depth 1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git  
    - name: debug show tree
      run: ls
