name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev
          sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache 
          sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar

    - name: Clone kernel source
      run: git clone --branch begonia-r-oss --depth 1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git

    - name: Clone Proton Clang
      run: git clone --depth 1 https://github.com/kdrag0n/proton-clang.git

    - name: Set up environment variables
      run: |
          echo "CC=$PWD/proton-clang/bin/clang" >> $GITHUB_ENV
          echo "CXX=$PWD/proton-clang/bin/clang++" >> $GITHUB_ENV
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=$PWD/proton-clang/bin/aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE_ARM32=$PWD/proton-clang/bin/arm-linux-gnueabi-" >> $GITHUB_ENV
          echo "LD=$PWD/proton-clang/bin/ld.lld" >> $GITHUB_ENV
          echo "AR=$PWD/proton-clang/bin/llvm-ar" >> $GITHUB_ENV
          echo "NM=$PWD/proton-clang/bin/llvm-nm" >> $GITHUB_ENV
          echo "STRIP=$PWD/proton-clang/bin/llvm-strip" >> $GITHUB_ENV
          echo "OBJCOPY=$PWD/proton-clang/bin/llvm-objcopy" >> $GITHUB_ENV
          echo "OBJDUMP=$PWD/proton-clang/bin/llvm-objdump" >> $GITHUB_ENV
          echo "READELF=$PWD/proton-clang/bin/llvm-readelf" >> $GITHUB_ENV
          echo "OBJSIZE=$PWD/proton-clang/bin/llvm-size" >> $GITHUB_ENV
          echo "LDGOLD=$PWD/proton-clang/bin/aarch64-linux-gnu-ld.gold" >> $GITHUB_ENV
          echo "LLVM_AR=$PWD/proton-clang/bin/llvm-ar" >> $GITHUB_ENV
          echo "LLVM_DIS=$PWD/proton-clang/bin/llvm-dis" >> $GITHUB_ENV
          echo "Clang toolchain setup complete."

    - name: Configure kernel
      run: |
          cd Xiaomi_Kernel_OpenSource
          make begonia_defconfig

    - name: Compile kernel
      run: |
          cd Xiaomi_Kernel_OpenSource
          make -j$(nproc)