name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev
          sudo apt-get install -y curl git ftp lftp wget libarchive-tools ccache 
          sudo apt-get install -y zip unzip tar gzip bzip2 rar unrar

    - name: Clone kernel source
      run: git clone --branch begonia-r-oss --depth 1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git

    - name: Clone Proton Clang
      run: git clone --depth 1 https://github.com/kdrag0n/proton-clang.git

    - name: Set up environment variables
      run: |
          echo "CC=$PWD/proton-clang/bin/clang" >> $GITHUB_ENV
          echo "CXX=$PWD/proton-clang/bin/clang++" >> $GITHUB_ENV
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV # 简化 CROSS_COMPILE
          echo "CROSS_COMPILE_ARM32=arm-linux-gnueabi-" >> $GITHUB_ENV # 简化 CROSS_COMPILE_ARM32
          echo "PATH=$PWD/proton-clang/bin:$PATH" >> $GITHUB_ENV # 将 clang 工具链加入 PATH
          echo "Clang toolchain setup complete."

    - name: Configure kernel
      run: |
          cd Xiaomi_Kernel_OpenSource
          make LLVM=1 begonia_user_defconfig

    - name: Compile kernel
      run: |
          cd Xiaomi_Kernel_OpenSource
          make LLVM=1 -j$(nproc)